//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.cim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import eu.adapt4ee._2012.schema.kpi.TEventTrace;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventTrace" type="{http://www.adapt4ee.eu/2012/schema/kpi/}tEventTrace"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventTrace"
})
@XmlRootElement(name = "EventTraceImport")
public class EventTraceImport {

    @XmlElement(required = true)
    protected TEventTrace eventTrace;

    /**
     * Gets the value of the eventTrace property.
     * 
     * @return
     *     possible object is
     *     {@link TEventTrace }
     *     
     */
    public TEventTrace getEventTrace() {
        return eventTrace;
    }

    /**
     * Sets the value of the eventTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEventTrace }
     *     
     */
    public void setEventTrace(TEventTrace value) {
        this.eventTrace = value;
    }

}
