//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.cim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.adapt4ee._2012.schema.cim package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EventTraceCount_QNAME = new QName("http://www.adapt4ee.eu/2012/schema/cim/", "EventTraceCount");
    private final static QName _EventTraceMaxTime_QNAME = new QName("http://www.adapt4ee.eu/2012/schema/cim/", "EventTraceMaxTime");
    private final static QName _EventTraceMinTime_QNAME = new QName("http://www.adapt4ee.eu/2012/schema/cim/", "EventTraceMinTime");
    private final static QName _ASMInput_QNAME = new QName("http://www.adapt4ee.eu/2012/schema/cim/", "ASMInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.adapt4ee._2012.schema.cim
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimulationFile }
     * 
     */
    public SimulationFile createSimulationFile() {
        return new SimulationFile();
    }

    /**
     * Create an instance of {@link EventsStats }
     * 
     */
    public EventsStats createEventsStats() {
        return new EventsStats();
    }

    /**
     * Create an instance of {@link MeasurementFile }
     * 
     */
    public MeasurementFile createMeasurementFile() {
        return new MeasurementFile();
    }

    /**
     * Create an instance of {@link ListOfOccupants }
     * 
     */
    public ListOfOccupants createListOfOccupants() {
        return new ListOfOccupants();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes }
     * 
     */
    public EventsStats.EventTimes createEventsStatsEventTimes() {
        return new EventsStats.EventTimes();
    }

    /**
     * Create an instance of {@link SimulationFile.Simulations }
     * 
     */
    public SimulationFile.Simulations createSimulationFileSimulations() {
        return new SimulationFile.Simulations();
    }

    /**
     * Create an instance of {@link SimulationFile.Simulations.SimulationCase }
     * 
     */
    public SimulationFile.Simulations.SimulationCase createSimulationFileSimulationsSimulationCase() {
        return new SimulationFile.Simulations.SimulationCase();
    }

    /**
     * Create an instance of {@link TTrainedTemplate }
     * 
     */
    public TTrainedTemplate createTTrainedTemplate() {
        return new TTrainedTemplate();
    }

    /**
     * Create an instance of {@link TTrainedTemplate.SpaceTemplate }
     * 
     */
    public TTrainedTemplate.SpaceTemplate createTTrainedTemplateSpaceTemplate() {
        return new TTrainedTemplate.SpaceTemplate();
    }

    /**
     * Create an instance of {@link PropertySets }
     * 
     */
    public PropertySets createPropertySets() {
        return new PropertySets();
    }

    /**
     * Create an instance of {@link ListOfHVACs }
     * 
     */
    public ListOfHVACs createListOfHVACs() {
        return new ListOfHVACs();
    }

    /**
     * Create an instance of {@link ListOfSensors }
     * 
     */
    public ListOfSensors createListOfSensors() {
        return new ListOfSensors();
    }

    /**
     * Create an instance of {@link DeviceDiscovered }
     * 
     */
    public DeviceDiscovered createDeviceDiscovered() {
        return new DeviceDiscovered();
    }

    /**
     * Create an instance of {@link ListOfMeasurementFileIDs }
     * 
     */
    public ListOfMeasurementFileIDs createListOfMeasurementFileIDs() {
        return new ListOfMeasurementFileIDs();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link ListOfRoles }
     * 
     */
    public ListOfRoles createListOfRoles() {
        return new ListOfRoles();
    }

    /**
     * Create an instance of {@link EventsImport }
     * 
     */
    public EventsImport createEventsImport() {
        return new EventsImport();
    }

    /**
     * Create an instance of {@link BuildingExport }
     * 
     */
    public BuildingExport createBuildingExport() {
        return new BuildingExport();
    }

    /**
     * Create an instance of {@link BPMImport }
     * 
     */
    public BPMImport createBPMImport() {
        return new BPMImport();
    }

    /**
     * Create an instance of {@link ListOfLightings }
     * 
     */
    public ListOfLightings createListOfLightings() {
        return new ListOfLightings();
    }

    /**
     * Create an instance of {@link EventsStats.EventNumbers }
     * 
     */
    public EventsStats.EventNumbers createEventsStatsEventNumbers() {
        return new EventsStats.EventNumbers();
    }

    /**
     * Create an instance of {@link EventTraceImport }
     * 
     */
    public EventTraceImport createEventTraceImport() {
        return new EventTraceImport();
    }

    /**
     * Create an instance of {@link ExtensionFile }
     * 
     */
    public ExtensionFile createExtensionFile() {
        return new ExtensionFile();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link ListOfZones }
     * 
     */
    public ListOfZones createListOfZones() {
        return new ListOfZones();
    }

    /**
     * Create an instance of {@link ListOfEvents }
     * 
     */
    public ListOfEvents createListOfEvents() {
        return new ListOfEvents();
    }

    /**
     * Create an instance of {@link MeasurementFile.Events }
     * 
     */
    public MeasurementFile.Events createMeasurementFileEvents() {
        return new MeasurementFile.Events();
    }

    /**
     * Create an instance of {@link MeasurementFile.Measurements }
     * 
     */
    public MeasurementFile.Measurements createMeasurementFileMeasurements() {
        return new MeasurementFile.Measurements();
    }

    /**
     * Create an instance of {@link MeasurementFile.Processes }
     * 
     */
    public MeasurementFile.Processes createMeasurementFileProcesses() {
        return new MeasurementFile.Processes();
    }

    /**
     * Create an instance of {@link MeasurementFile.Roles }
     * 
     */
    public MeasurementFile.Roles createMeasurementFileRoles() {
        return new MeasurementFile.Roles();
    }

    /**
     * Create an instance of {@link ListOfOccupants.Occupant }
     * 
     */
    public ListOfOccupants.Occupant createListOfOccupantsOccupant() {
        return new ListOfOccupants.Occupant();
    }

    /**
     * Create an instance of {@link ListOfEquipments }
     * 
     */
    public ListOfEquipments createListOfEquipments() {
        return new ListOfEquipments();
    }

    /**
     * Create an instance of {@link BuildingImport }
     * 
     */
    public BuildingImport createBuildingImport() {
        return new BuildingImport();
    }

    /**
     * Create an instance of {@link MeasurementsImport }
     * 
     */
    public MeasurementsImport createMeasurementsImport() {
        return new MeasurementsImport();
    }

    /**
     * Create an instance of {@link ListOfProcesses }
     * 
     */
    public ListOfProcesses createListOfProcesses() {
        return new ListOfProcesses();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.OccupantTrajectoryTime }
     * 
     */
    public EventsStats.EventTimes.OccupantTrajectoryTime createEventsStatsEventTimesOccupantTrajectoryTime() {
        return new EventsStats.EventTimes.OccupantTrajectoryTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.OccupantMovedTime }
     * 
     */
    public EventsStats.EventTimes.OccupantMovedTime createEventsStatsEventTimesOccupantMovedTime() {
        return new EventsStats.EventTimes.OccupantMovedTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.EquipmentUsedTime }
     * 
     */
    public EventsStats.EventTimes.EquipmentUsedTime createEventsStatsEventTimesEquipmentUsedTime() {
        return new EventsStats.EventTimes.EquipmentUsedTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.SpaceEnvironmentChangeTime }
     * 
     */
    public EventsStats.EventTimes.SpaceEnvironmentChangeTime createEventsStatsEventTimesSpaceEnvironmentChangeTime() {
        return new EventsStats.EventTimes.SpaceEnvironmentChangeTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.ExternalEnvironmentChangedTime }
     * 
     */
    public EventsStats.EventTimes.ExternalEnvironmentChangedTime createEventsStatsEventTimesExternalEnvironmentChangedTime() {
        return new EventsStats.EventTimes.ExternalEnvironmentChangedTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.HVACChangeTime }
     * 
     */
    public EventsStats.EventTimes.HVACChangeTime createEventsStatsEventTimesHVACChangeTime() {
        return new EventsStats.EventTimes.HVACChangeTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.LightingChangeTime }
     * 
     */
    public EventsStats.EventTimes.LightingChangeTime createEventsStatsEventTimesLightingChangeTime() {
        return new EventsStats.EventTimes.LightingChangeTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.SpaceOccupancyTime }
     * 
     */
    public EventsStats.EventTimes.SpaceOccupancyTime createEventsStatsEventTimesSpaceOccupancyTime() {
        return new EventsStats.EventTimes.SpaceOccupancyTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.SpaceMovementTime }
     * 
     */
    public EventsStats.EventTimes.SpaceMovementTime createEventsStatsEventTimesSpaceMovementTime() {
        return new EventsStats.EventTimes.SpaceMovementTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.SpaceOccupantPossitionsTime }
     * 
     */
    public EventsStats.EventTimes.SpaceOccupantPossitionsTime createEventsStatsEventTimesSpaceOccupantPossitionsTime() {
        return new EventsStats.EventTimes.SpaceOccupantPossitionsTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.CurrentTime }
     * 
     */
    public EventsStats.EventTimes.CurrentTime createEventsStatsEventTimesCurrentTime() {
        return new EventsStats.EventTimes.CurrentTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.VoltageTime }
     * 
     */
    public EventsStats.EventTimes.VoltageTime createEventsStatsEventTimesVoltageTime() {
        return new EventsStats.EventTimes.VoltageTime();
    }

    /**
     * Create an instance of {@link EventsStats.EventTimes.EnergyTime }
     * 
     */
    public EventsStats.EventTimes.EnergyTime createEventsStatsEventTimesEnergyTime() {
        return new EventsStats.EventTimes.EnergyTime();
    }

    /**
     * Create an instance of {@link SimulationFile.Simulations.SimulationCase.Roles }
     * 
     */
    public SimulationFile.Simulations.SimulationCase.Roles createSimulationFileSimulationsSimulationCaseRoles() {
        return new SimulationFile.Simulations.SimulationCase.Roles();
    }

    /**
     * Create an instance of {@link TTrainedTemplate.RoleTemplate }
     * 
     */
    public TTrainedTemplate.RoleTemplate createTTrainedTemplateRoleTemplate() {
        return new TTrainedTemplate.RoleTemplate();
    }

    /**
     * Create an instance of {@link TTrainedTemplate.SpaceTemplate.Equipment }
     * 
     */
    public TTrainedTemplate.SpaceTemplate.Equipment createTTrainedTemplateSpaceTemplateEquipment() {
        return new TTrainedTemplate.SpaceTemplate.Equipment();
    }

    /**
     * Create an instance of {@link TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy }
     * 
     */
    public TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy createTTrainedTemplateSpaceTemplateDailyMeanOccupancy() {
        return new TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.adapt4ee.eu/2012/schema/cim/", name = "EventTraceCount")
    public JAXBElement<Long> createEventTraceCount(Long value) {
        return new JAXBElement<Long>(_EventTraceCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.adapt4ee.eu/2012/schema/cim/", name = "EventTraceMaxTime")
    public JAXBElement<XMLGregorianCalendar> createEventTraceMaxTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EventTraceMaxTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.adapt4ee.eu/2012/schema/cim/", name = "EventTraceMinTime")
    public JAXBElement<XMLGregorianCalendar> createEventTraceMinTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EventTraceMinTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTrainedTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.adapt4ee.eu/2012/schema/cim/", name = "ASMInput")
    public JAXBElement<TTrainedTemplate> createASMInput(TTrainedTemplate value) {
        return new JAXBElement<TTrainedTemplate>(_ASMInput_QNAME, TTrainedTemplate.class, null, value);
    }

}
