//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.cim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.adapt4ee._2012.schema.bim.TEquipmentTypeCharacteristics;
import eu.adapt4ee._2012.schema.bpm.TProcessType;
import eu.adapt4ee._2012.schema.bpm.TRole;
import eu.adapt4ee._2012.schema.bpm.TSkeletonActivityType;
import eu.adapt4ee._2012.schema.units.BuildingTypeEnum;
import eu.adapt4ee._2012.schema.units.IntEquipTypeEnum;
import eu.adapt4ee._2012.schema.units.SpaceTypeEnum;
import eu.adapt4ee._2012.schema.units.TDistribution;
import eu.adapt4ee._2012.schema.units.TEnvironmentComfortValues;
import eu.adapt4ee._2012.schema.units.TPeopleClothingValue;
import eu.adapt4ee._2012.schema.units.TPeopleHeatGainValue;
import eu.adapt4ee._2012.schema.units.TPeopleNumberValue;


/**
 * <p>Java class for tTrainedTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrainedTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildingType" type="{http://www.adapt4ee.eu/2012/schema/units/}buildingTypeEnum"/>
 *         &lt;element name="roleTemplate" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="roleRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="clothing" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleClothingValue"/>
 *                   &lt;element name="metabolicRate" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleHeatGainValue"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="equipmentTemplate" type="{http://www.adapt4ee.eu/2012/schema/bim/}tEquipmentTypeCharacteristics" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="spaceTemplate" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="spaceTypeRef" type="{http://www.adapt4ee.eu/2012/schema/units/}spaceTypeEnum" minOccurs="0"/>
 *                   &lt;element name="equipment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="type" type="{http://www.adapt4ee.eu/2012/schema/units/}intEquipTypeEnum"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="maxOccupantLoad" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleNumberValue" minOccurs="0"/>
 *                   &lt;element name="dailyMeanOccupancy" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="occupantRole" type="{http://www.adapt4ee.eu/2012/schema/bpm/}tRole" minOccurs="0"/>
 *                             &lt;element name="meanOccupancy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="operatingEnvironmentValues" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnvironmentComfortValues"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="activity" type="{http://www.adapt4ee.eu/2012/schema/bpm/}tSkeletonActivityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="process" type="{http://www.adapt4ee.eu/2012/schema/bpm/}tProcessType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="processTemplate" type="{http://www.adapt4ee.eu/2012/schema/units/}tDistribution" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrainedTemplate", propOrder = {
    "id",
    "buildingType",
    "roleTemplate",
    "equipmentTemplate",
    "spaceTemplate",
    "activity",
    "process",
    "processTemplate"
})
public class TTrainedTemplate {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected BuildingTypeEnum buildingType;
    protected List<TTrainedTemplate.RoleTemplate> roleTemplate;
    protected List<TEquipmentTypeCharacteristics> equipmentTemplate;
    protected List<TTrainedTemplate.SpaceTemplate> spaceTemplate;
    protected List<TSkeletonActivityType> activity;
    protected List<TProcessType> process;
    protected List<TDistribution> processTemplate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the buildingType property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingTypeEnum }
     *     
     */
    public BuildingTypeEnum getBuildingType() {
        return buildingType;
    }

    /**
     * Sets the value of the buildingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingTypeEnum }
     *     
     */
    public void setBuildingType(BuildingTypeEnum value) {
        this.buildingType = value;
    }

    /**
     * Gets the value of the roleTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTrainedTemplate.RoleTemplate }
     * 
     * 
     */
    public List<TTrainedTemplate.RoleTemplate> getRoleTemplate() {
        if (roleTemplate == null) {
            roleTemplate = new ArrayList<TTrainedTemplate.RoleTemplate>();
        }
        return this.roleTemplate;
    }

    /**
     * Gets the value of the equipmentTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEquipmentTypeCharacteristics }
     * 
     * 
     */
    public List<TEquipmentTypeCharacteristics> getEquipmentTemplate() {
        if (equipmentTemplate == null) {
            equipmentTemplate = new ArrayList<TEquipmentTypeCharacteristics>();
        }
        return this.equipmentTemplate;
    }

    /**
     * Gets the value of the spaceTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spaceTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpaceTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTrainedTemplate.SpaceTemplate }
     * 
     * 
     */
    public List<TTrainedTemplate.SpaceTemplate> getSpaceTemplate() {
        if (spaceTemplate == null) {
            spaceTemplate = new ArrayList<TTrainedTemplate.SpaceTemplate>();
        }
        return this.spaceTemplate;
    }

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSkeletonActivityType }
     * 
     * 
     */
    public List<TSkeletonActivityType> getActivity() {
        if (activity == null) {
            activity = new ArrayList<TSkeletonActivityType>();
        }
        return this.activity;
    }

    /**
     * Gets the value of the process property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the process property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TProcessType }
     * 
     * 
     */
    public List<TProcessType> getProcess() {
        if (process == null) {
            process = new ArrayList<TProcessType>();
        }
        return this.process;
    }

    /**
     * Gets the value of the processTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDistribution }
     * 
     * 
     */
    public List<TDistribution> getProcessTemplate() {
        if (processTemplate == null) {
            processTemplate = new ArrayList<TDistribution>();
        }
        return this.processTemplate;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="roleRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="clothing" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleClothingValue"/>
     *         &lt;element name="metabolicRate" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleHeatGainValue"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roleRef",
        "clothing",
        "metabolicRate"
    })
    public static class RoleTemplate {

        @XmlElement(required = true)
        protected String roleRef;
        @XmlElement(required = true)
        protected TPeopleClothingValue clothing;
        @XmlElement(required = true)
        protected TPeopleHeatGainValue metabolicRate;

        /**
         * Gets the value of the roleRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoleRef() {
            return roleRef;
        }

        /**
         * Sets the value of the roleRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoleRef(String value) {
            this.roleRef = value;
        }

        /**
         * Gets the value of the clothing property.
         * 
         * @return
         *     possible object is
         *     {@link TPeopleClothingValue }
         *     
         */
        public TPeopleClothingValue getClothing() {
            return clothing;
        }

        /**
         * Sets the value of the clothing property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPeopleClothingValue }
         *     
         */
        public void setClothing(TPeopleClothingValue value) {
            this.clothing = value;
        }

        /**
         * Gets the value of the metabolicRate property.
         * 
         * @return
         *     possible object is
         *     {@link TPeopleHeatGainValue }
         *     
         */
        public TPeopleHeatGainValue getMetabolicRate() {
            return metabolicRate;
        }

        /**
         * Sets the value of the metabolicRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPeopleHeatGainValue }
         *     
         */
        public void setMetabolicRate(TPeopleHeatGainValue value) {
            this.metabolicRate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="spaceTypeRef" type="{http://www.adapt4ee.eu/2012/schema/units/}spaceTypeEnum" minOccurs="0"/>
     *         &lt;element name="equipment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="type" type="{http://www.adapt4ee.eu/2012/schema/units/}intEquipTypeEnum"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="maxOccupantLoad" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleNumberValue" minOccurs="0"/>
     *         &lt;element name="dailyMeanOccupancy" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="occupantRole" type="{http://www.adapt4ee.eu/2012/schema/bpm/}tRole" minOccurs="0"/>
     *                   &lt;element name="meanOccupancy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="operatingEnvironmentValues" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnvironmentComfortValues"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "spaceTypeRef",
        "equipment",
        "maxOccupantLoad",
        "dailyMeanOccupancy",
        "operatingEnvironmentValues"
    })
    public static class SpaceTemplate {

        protected SpaceTypeEnum spaceTypeRef;
        protected List<TTrainedTemplate.SpaceTemplate.Equipment> equipment;
        protected TPeopleNumberValue maxOccupantLoad;
        protected List<TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy> dailyMeanOccupancy;
        @XmlElement(required = true)
        protected TEnvironmentComfortValues operatingEnvironmentValues;

        /**
         * Gets the value of the spaceTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link SpaceTypeEnum }
         *     
         */
        public SpaceTypeEnum getSpaceTypeRef() {
            return spaceTypeRef;
        }

        /**
         * Sets the value of the spaceTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpaceTypeEnum }
         *     
         */
        public void setSpaceTypeRef(SpaceTypeEnum value) {
            this.spaceTypeRef = value;
        }

        /**
         * Gets the value of the equipment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the equipment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEquipment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTrainedTemplate.SpaceTemplate.Equipment }
         * 
         * 
         */
        public List<TTrainedTemplate.SpaceTemplate.Equipment> getEquipment() {
            if (equipment == null) {
                equipment = new ArrayList<TTrainedTemplate.SpaceTemplate.Equipment>();
            }
            return this.equipment;
        }

        /**
         * Gets the value of the maxOccupantLoad property.
         * 
         * @return
         *     possible object is
         *     {@link TPeopleNumberValue }
         *     
         */
        public TPeopleNumberValue getMaxOccupantLoad() {
            return maxOccupantLoad;
        }

        /**
         * Sets the value of the maxOccupantLoad property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPeopleNumberValue }
         *     
         */
        public void setMaxOccupantLoad(TPeopleNumberValue value) {
            this.maxOccupantLoad = value;
        }

        /**
         * Gets the value of the dailyMeanOccupancy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dailyMeanOccupancy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDailyMeanOccupancy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy }
         * 
         * 
         */
        public List<TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy> getDailyMeanOccupancy() {
            if (dailyMeanOccupancy == null) {
                dailyMeanOccupancy = new ArrayList<TTrainedTemplate.SpaceTemplate.DailyMeanOccupancy>();
            }
            return this.dailyMeanOccupancy;
        }

        /**
         * Gets the value of the operatingEnvironmentValues property.
         * 
         * @return
         *     possible object is
         *     {@link TEnvironmentComfortValues }
         *     
         */
        public TEnvironmentComfortValues getOperatingEnvironmentValues() {
            return operatingEnvironmentValues;
        }

        /**
         * Sets the value of the operatingEnvironmentValues property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnvironmentComfortValues }
         *     
         */
        public void setOperatingEnvironmentValues(TEnvironmentComfortValues value) {
            this.operatingEnvironmentValues = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="occupantRole" type="{http://www.adapt4ee.eu/2012/schema/bpm/}tRole" minOccurs="0"/>
         *         &lt;element name="meanOccupancy" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "occupantRole",
            "meanOccupancy"
        })
        public static class DailyMeanOccupancy {

            protected TRole occupantRole;
            protected int meanOccupancy;

            /**
             * Gets the value of the occupantRole property.
             * 
             * @return
             *     possible object is
             *     {@link TRole }
             *     
             */
            public TRole getOccupantRole() {
                return occupantRole;
            }

            /**
             * Sets the value of the occupantRole property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRole }
             *     
             */
            public void setOccupantRole(TRole value) {
                this.occupantRole = value;
            }

            /**
             * Gets the value of the meanOccupancy property.
             * 
             */
            public int getMeanOccupancy() {
                return meanOccupancy;
            }

            /**
             * Sets the value of the meanOccupancy property.
             * 
             */
            public void setMeanOccupancy(int value) {
                this.meanOccupancy = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="type" type="{http://www.adapt4ee.eu/2012/schema/units/}intEquipTypeEnum"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "amount",
            "type"
        })
        public static class Equipment {

            protected int amount;
            @XmlElement(required = true)
            protected IntEquipTypeEnum type;

            /**
             * Gets the value of the amount property.
             * 
             */
            public int getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             */
            public void setAmount(int value) {
                this.amount = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link IntEquipTypeEnum }
             *     
             */
            public IntEquipTypeEnum getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link IntEquipTypeEnum }
             *     
             */
            public void setType(IntEquipTypeEnum value) {
                this.type = value;
            }

        }

    }

}
