//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.bim;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.adapt4ee._2012.schema.bim package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.adapt4ee._2012.schema.bim
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSpace }
     * 
     */
    public TSpace createTSpace() {
        return new TSpace();
    }

    /**
     * Create an instance of {@link TBuilding }
     * 
     */
    public TBuilding createTBuilding() {
        return new TBuilding();
    }

    /**
     * Create an instance of {@link THVAC }
     * 
     */
    public THVAC createTHVAC() {
        return new THVAC();
    }

    /**
     * Create an instance of {@link TLighting }
     * 
     */
    public TLighting createTLighting() {
        return new TLighting();
    }

    /**
     * Create an instance of {@link TEquipment }
     * 
     */
    public TEquipment createTEquipment() {
        return new TEquipment();
    }

    /**
     * Create an instance of {@link TEquipmentTypeCharacteristics }
     * 
     */
    public TEquipmentTypeCharacteristics createTEquipmentTypeCharacteristics() {
        return new TEquipmentTypeCharacteristics();
    }

    /**
     * Create an instance of {@link TGroupOfSpaces }
     * 
     */
    public TGroupOfSpaces createTGroupOfSpaces() {
        return new TGroupOfSpaces();
    }

    /**
     * Create an instance of {@link TSpace.Equipments }
     * 
     */
    public TSpace.Equipments createTSpaceEquipments() {
        return new TSpace.Equipments();
    }

    /**
     * Create an instance of {@link TSpace.Lightings }
     * 
     */
    public TSpace.Lightings createTSpaceLightings() {
        return new TSpace.Lightings();
    }

    /**
     * Create an instance of {@link TBuilding.Zones }
     * 
     */
    public TBuilding.Zones createTBuildingZones() {
        return new TBuilding.Zones();
    }

    /**
     * Create an instance of {@link TBuilding.Sensors }
     * 
     */
    public TBuilding.Sensors createTBuildingSensors() {
        return new TBuilding.Sensors();
    }

    /**
     * Create an instance of {@link TBuilding.EquipmentTypes }
     * 
     */
    public TBuilding.EquipmentTypes createTBuildingEquipmentTypes() {
        return new TBuilding.EquipmentTypes();
    }

    /**
     * Create an instance of {@link TBuilding.HVACs }
     * 
     */
    public TBuilding.HVACs createTBuildingHVACs() {
        return new TBuilding.HVACs();
    }

}
