//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.bim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import eu.adapt4ee._2012.schema.units.IntEquipTypeEnum;
import eu.adapt4ee._2012.schema.units.TEnergyValue;


/**
 * Equipment type concept
 * 
 * <p>Java class for tEquipmentTypeCharacteristics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEquipmentTypeCharacteristics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="equipmentTypeName" type="{http://www.adapt4ee.eu/2012/schema/units/}intEquipTypeEnum"/>
 *         &lt;element name="energyConsumptionPerTime" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *         &lt;element name="heatProduction" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *         &lt;element name="timeOfSingleTaskUsage" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEquipmentTypeCharacteristics", propOrder = {
    "id",
    "equipmentTypeName",
    "energyConsumptionPerTime",
    "heatProduction",
    "timeOfSingleTaskUsage"
})
public class TEquipmentTypeCharacteristics {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected IntEquipTypeEnum equipmentTypeName;
    protected TEnergyValue energyConsumptionPerTime;
    protected TEnergyValue heatProduction;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timeOfSingleTaskUsage;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the equipmentTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link IntEquipTypeEnum }
     *     
     */
    public IntEquipTypeEnum getEquipmentTypeName() {
        return equipmentTypeName;
    }

    /**
     * Sets the value of the equipmentTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntEquipTypeEnum }
     *     
     */
    public void setEquipmentTypeName(IntEquipTypeEnum value) {
        this.equipmentTypeName = value;
    }

    /**
     * Gets the value of the energyConsumptionPerTime property.
     * 
     * @return
     *     possible object is
     *     {@link TEnergyValue }
     *     
     */
    public TEnergyValue getEnergyConsumptionPerTime() {
        return energyConsumptionPerTime;
    }

    /**
     * Sets the value of the energyConsumptionPerTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEnergyValue }
     *     
     */
    public void setEnergyConsumptionPerTime(TEnergyValue value) {
        this.energyConsumptionPerTime = value;
    }

    /**
     * Gets the value of the heatProduction property.
     * 
     * @return
     *     possible object is
     *     {@link TEnergyValue }
     *     
     */
    public TEnergyValue getHeatProduction() {
        return heatProduction;
    }

    /**
     * Sets the value of the heatProduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEnergyValue }
     *     
     */
    public void setHeatProduction(TEnergyValue value) {
        this.heatProduction = value;
    }

    /**
     * Gets the value of the timeOfSingleTaskUsage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfSingleTaskUsage() {
        return timeOfSingleTaskUsage;
    }

    /**
     * Sets the value of the timeOfSingleTaskUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfSingleTaskUsage(XMLGregorianCalendar value) {
        this.timeOfSingleTaskUsage = value;
    }

}
