//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.bim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.adapt4ee._2012.schema.units.TEmissionValue;
import eu.adapt4ee._2012.schema.units.TEnergyValue;


/**
 * <p>Java class for tHVAC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tHVAC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *         &lt;element name="spaceRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sensorRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="emissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tHVAC", propOrder = {
    "id",
    "consumption",
    "spaceRef",
    "sensorRef",
    "emissions"
})
public class THVAC {

    @XmlElement(required = true)
    protected String id;
    protected TEnergyValue consumption;
    protected List<String> spaceRef;
    protected List<String> sensorRef;
    protected TEmissionValue emissions;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the consumption property.
     * 
     * @return
     *     possible object is
     *     {@link TEnergyValue }
     *     
     */
    public TEnergyValue getConsumption() {
        return consumption;
    }

    /**
     * Sets the value of the consumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEnergyValue }
     *     
     */
    public void setConsumption(TEnergyValue value) {
        this.consumption = value;
    }

    /**
     * Gets the value of the spaceRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spaceRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpaceRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpaceRef() {
        if (spaceRef == null) {
            spaceRef = new ArrayList<String>();
        }
        return this.spaceRef;
    }

    /**
     * Gets the value of the sensorRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSensorRef() {
        if (sensorRef == null) {
            sensorRef = new ArrayList<String>();
        }
        return this.sensorRef;
    }

    /**
     * Gets the value of the emissions property.
     * 
     * @return
     *     possible object is
     *     {@link TEmissionValue }
     *     
     */
    public TEmissionValue getEmissions() {
        return emissions;
    }

    /**
     * Sets the value of the emissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEmissionValue }
     *     
     */
    public void setEmissions(TEmissionValue value) {
        this.emissions = value;
    }

}
