//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.bpm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.adapt4ee._2012.schema.bpm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.adapt4ee._2012.schema.bpm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSkeletonActivityType }
     * 
     */
    public TSkeletonActivityType createTSkeletonActivityType() {
        return new TSkeletonActivityType();
    }

    /**
     * Create an instance of {@link TRole }
     * 
     */
    public TRole createTRole() {
        return new TRole();
    }

    /**
     * Create an instance of {@link TProcessType }
     * 
     */
    public TProcessType createTProcessType() {
        return new TProcessType();
    }

    /**
     * Create an instance of {@link TSkeletonActivityType.UsedEquipment }
     * 
     */
    public TSkeletonActivityType.UsedEquipment createTSkeletonActivityTypeUsedEquipment() {
        return new TSkeletonActivityType.UsedEquipment();
    }

    /**
     * Create an instance of {@link TSkeletonActivityType.RoleInvolved }
     * 
     */
    public TSkeletonActivityType.RoleInvolved createTSkeletonActivityTypeRoleInvolved() {
        return new TSkeletonActivityType.RoleInvolved();
    }

    /**
     * Create an instance of {@link TSkeletonActivityType.PreviousActivityRef }
     * 
     */
    public TSkeletonActivityType.PreviousActivityRef createTSkeletonActivityTypePreviousActivityRef() {
        return new TSkeletonActivityType.PreviousActivityRef();
    }

    /**
     * Create an instance of {@link TSkeletonActivityType.NextActivityRef }
     * 
     */
    public TSkeletonActivityType.NextActivityRef createTSkeletonActivityTypeNextActivityRef() {
        return new TSkeletonActivityType.NextActivityRef();
    }

}
