//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.bpm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.Duration;
import eu.adapt4ee._2012.schema.units.IntEquipTypeEnum;
import eu.adapt4ee._2012.schema.units.SpaceTypeEnum;
import eu.adapt4ee._2012.schema.units.TEnvironmentComfortValues;
import eu.adapt4ee._2012.schema.units.TFrequencyValue;
import eu.adapt4ee._2012.schema.units.TPeopleClothingValue;
import eu.adapt4ee._2012.schema.units.TPeopleHeatGainValue;
import eu.adapt4ee._2012.schema.units.TUnitlessValue;


/**
 * 
 * 				Skeleton activity is a simplified activiti encapsulating
 * 				several tasks of the original business process.
 * 			
 * 
 * <p>Java class for tSkeletonActivityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSkeletonActivityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usedSpaceType" type="{http://www.adapt4ee.eu/2012/schema/units/}spaceTypeEnum" maxOccurs="unbounded"/>
 *         &lt;element name="usedEquipment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="equipmentTypeRef" type="{http://www.adapt4ee.eu/2012/schema/units/}intEquipTypeEnum"/>
 *                   &lt;element name="numberOf" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="numberOfUses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="timeOfUse" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *                   &lt;element name="equipmentIntensityMode" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RoleInvolved" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="roleRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="averageNumberOfPersons" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="occupantWorkIntensity" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleHeatGainValue"/>
 *                   &lt;element name="clothing" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleClothingValue"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="requiredEnvironment" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnvironmentComfortValues" minOccurs="0"/>
 *         &lt;element name="interruptable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="waitingTime" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="executionTime" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *         &lt;element name="transportTime" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="frequency" type="{http://www.adapt4ee.eu/2012/schema/units/}tFrequencyValue"/>
 *         &lt;element name="isBusinessActivity" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="previousActivityRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="likelihood" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nextActivityRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="likelihood" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSkeletonActivityType", propOrder = {
    "id",
    "name",
    "usedSpaceType",
    "usedEquipment",
    "roleInvolved",
    "requiredEnvironment",
    "interruptable",
    "waitingTime",
    "executionTime",
    "transportTime",
    "frequency",
    "isBusinessActivity",
    "previousActivityRef",
    "nextActivityRef"
})
public class TSkeletonActivityType {

    @XmlElement(required = true)
    protected String id;
    protected String name;
    @XmlElement(required = true)
    protected List<SpaceTypeEnum> usedSpaceType;
    protected List<TSkeletonActivityType.UsedEquipment> usedEquipment;
    @XmlElement(name = "RoleInvolved")
    protected List<TSkeletonActivityType.RoleInvolved> roleInvolved;
    protected TEnvironmentComfortValues requiredEnvironment;
    protected Boolean interruptable;
    protected Duration waitingTime;
    @XmlElement(required = true)
    protected Duration executionTime;
    protected Duration transportTime;
    @XmlElement(required = true)
    protected TFrequencyValue frequency;
    protected boolean isBusinessActivity;
    protected List<TSkeletonActivityType.PreviousActivityRef> previousActivityRef;
    protected List<TSkeletonActivityType.NextActivityRef> nextActivityRef;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the usedSpaceType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usedSpaceType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsedSpaceType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpaceTypeEnum }
     * 
     * 
     */
    public List<SpaceTypeEnum> getUsedSpaceType() {
        if (usedSpaceType == null) {
            usedSpaceType = new ArrayList<SpaceTypeEnum>();
        }
        return this.usedSpaceType;
    }

    /**
     * Gets the value of the usedEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usedEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsedEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSkeletonActivityType.UsedEquipment }
     * 
     * 
     */
    public List<TSkeletonActivityType.UsedEquipment> getUsedEquipment() {
        if (usedEquipment == null) {
            usedEquipment = new ArrayList<TSkeletonActivityType.UsedEquipment>();
        }
        return this.usedEquipment;
    }

    /**
     * Gets the value of the roleInvolved property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleInvolved property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleInvolved().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSkeletonActivityType.RoleInvolved }
     * 
     * 
     */
    public List<TSkeletonActivityType.RoleInvolved> getRoleInvolved() {
        if (roleInvolved == null) {
            roleInvolved = new ArrayList<TSkeletonActivityType.RoleInvolved>();
        }
        return this.roleInvolved;
    }

    /**
     * Gets the value of the requiredEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link TEnvironmentComfortValues }
     *     
     */
    public TEnvironmentComfortValues getRequiredEnvironment() {
        return requiredEnvironment;
    }

    /**
     * Sets the value of the requiredEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEnvironmentComfortValues }
     *     
     */
    public void setRequiredEnvironment(TEnvironmentComfortValues value) {
        this.requiredEnvironment = value;
    }

    /**
     * Gets the value of the interruptable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInterruptable() {
        return interruptable;
    }

    /**
     * Sets the value of the interruptable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInterruptable(Boolean value) {
        this.interruptable = value;
    }

    /**
     * Gets the value of the waitingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getWaitingTime() {
        return waitingTime;
    }

    /**
     * Sets the value of the waitingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setWaitingTime(Duration value) {
        this.waitingTime = value;
    }

    /**
     * Gets the value of the executionTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getExecutionTime() {
        return executionTime;
    }

    /**
     * Sets the value of the executionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setExecutionTime(Duration value) {
        this.executionTime = value;
    }

    /**
     * Gets the value of the transportTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTransportTime() {
        return transportTime;
    }

    /**
     * Sets the value of the transportTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTransportTime(Duration value) {
        this.transportTime = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link TFrequencyValue }
     *     
     */
    public TFrequencyValue getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFrequencyValue }
     *     
     */
    public void setFrequency(TFrequencyValue value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the isBusinessActivity property.
     * 
     */
    public boolean isIsBusinessActivity() {
        return isBusinessActivity;
    }

    /**
     * Sets the value of the isBusinessActivity property.
     * 
     */
    public void setIsBusinessActivity(boolean value) {
        this.isBusinessActivity = value;
    }

    /**
     * Gets the value of the previousActivityRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the previousActivityRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreviousActivityRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSkeletonActivityType.PreviousActivityRef }
     * 
     * 
     */
    public List<TSkeletonActivityType.PreviousActivityRef> getPreviousActivityRef() {
        if (previousActivityRef == null) {
            previousActivityRef = new ArrayList<TSkeletonActivityType.PreviousActivityRef>();
        }
        return this.previousActivityRef;
    }

    /**
     * Gets the value of the nextActivityRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nextActivityRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNextActivityRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSkeletonActivityType.NextActivityRef }
     * 
     * 
     */
    public List<TSkeletonActivityType.NextActivityRef> getNextActivityRef() {
        if (nextActivityRef == null) {
            nextActivityRef = new ArrayList<TSkeletonActivityType.NextActivityRef>();
        }
        return this.nextActivityRef;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="likelihood" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NextActivityRef {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "likelihood")
        protected Double likelihood;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the likelihood property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLikelihood() {
            return likelihood;
        }

        /**
         * Sets the value of the likelihood property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLikelihood(Double value) {
            this.likelihood = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="likelihood" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PreviousActivityRef {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "likelihood")
        protected Double likelihood;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the likelihood property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLikelihood() {
            return likelihood;
        }

        /**
         * Sets the value of the likelihood property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLikelihood(Double value) {
            this.likelihood = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="roleRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="averageNumberOfPersons" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="occupantWorkIntensity" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleHeatGainValue"/>
     *         &lt;element name="clothing" type="{http://www.adapt4ee.eu/2012/schema/units/}tPeopleClothingValue"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roleRef",
        "averageNumberOfPersons",
        "occupantWorkIntensity",
        "clothing"
    })
    public static class RoleInvolved {

        @XmlElement(required = true)
        protected String roleRef;
        protected Float averageNumberOfPersons;
        @XmlElement(required = true)
        protected TPeopleHeatGainValue occupantWorkIntensity;
        @XmlElement(required = true)
        protected TPeopleClothingValue clothing;

        /**
         * Gets the value of the roleRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoleRef() {
            return roleRef;
        }

        /**
         * Sets the value of the roleRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoleRef(String value) {
            this.roleRef = value;
        }

        /**
         * Gets the value of the averageNumberOfPersons property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAverageNumberOfPersons() {
            return averageNumberOfPersons;
        }

        /**
         * Sets the value of the averageNumberOfPersons property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAverageNumberOfPersons(Float value) {
            this.averageNumberOfPersons = value;
        }

        /**
         * Gets the value of the occupantWorkIntensity property.
         * 
         * @return
         *     possible object is
         *     {@link TPeopleHeatGainValue }
         *     
         */
        public TPeopleHeatGainValue getOccupantWorkIntensity() {
            return occupantWorkIntensity;
        }

        /**
         * Sets the value of the occupantWorkIntensity property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPeopleHeatGainValue }
         *     
         */
        public void setOccupantWorkIntensity(TPeopleHeatGainValue value) {
            this.occupantWorkIntensity = value;
        }

        /**
         * Gets the value of the clothing property.
         * 
         * @return
         *     possible object is
         *     {@link TPeopleClothingValue }
         *     
         */
        public TPeopleClothingValue getClothing() {
            return clothing;
        }

        /**
         * Sets the value of the clothing property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPeopleClothingValue }
         *     
         */
        public void setClothing(TPeopleClothingValue value) {
            this.clothing = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="equipmentTypeRef" type="{http://www.adapt4ee.eu/2012/schema/units/}intEquipTypeEnum"/>
     *         &lt;element name="numberOf" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="numberOfUses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="timeOfUse" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
     *         &lt;element name="equipmentIntensityMode" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equipmentTypeRef",
        "numberOf",
        "numberOfUses",
        "timeOfUse",
        "equipmentIntensityMode"
    })
    public static class UsedEquipment {

        @XmlElement(required = true)
        protected IntEquipTypeEnum equipmentTypeRef;
        protected int numberOf;
        protected Integer numberOfUses;
        protected Duration timeOfUse;
        @XmlElement(required = true)
        protected TUnitlessValue equipmentIntensityMode;

        /**
         * Gets the value of the equipmentTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link IntEquipTypeEnum }
         *     
         */
        public IntEquipTypeEnum getEquipmentTypeRef() {
            return equipmentTypeRef;
        }

        /**
         * Sets the value of the equipmentTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link IntEquipTypeEnum }
         *     
         */
        public void setEquipmentTypeRef(IntEquipTypeEnum value) {
            this.equipmentTypeRef = value;
        }

        /**
         * Gets the value of the numberOf property.
         * 
         */
        public int getNumberOf() {
            return numberOf;
        }

        /**
         * Sets the value of the numberOf property.
         * 
         */
        public void setNumberOf(int value) {
            this.numberOf = value;
        }

        /**
         * Gets the value of the numberOfUses property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberOfUses() {
            return numberOfUses;
        }

        /**
         * Sets the value of the numberOfUses property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberOfUses(Integer value) {
            this.numberOfUses = value;
        }

        /**
         * Gets the value of the timeOfUse property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        public Duration getTimeOfUse() {
            return timeOfUse;
        }

        /**
         * Sets the value of the timeOfUse property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        public void setTimeOfUse(Duration value) {
            this.timeOfUse = value;
        }

        /**
         * Gets the value of the equipmentIntensityMode property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getEquipmentIntensityMode() {
            return equipmentIntensityMode;
        }

        /**
         * Sets the value of the equipmentIntensityMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setEquipmentIntensityMode(TUnitlessValue value) {
            this.equipmentIntensityMode = value;
        }

    }

}
