//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.event;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.adapt4ee._2012.schema.units.TTrajectoryPoint;
import eu.adapt4ee._2012.schema.units.TTrajectoryPointMini;


/**
 * <p>Java class for tOccupantTrajectory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOccupantTrajectory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="occupantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spaceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="occupantTrajectory" type="{http://www.adapt4ee.eu/2012/schema/units/}tTrajectoryPoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="a" type="{http://www.adapt4ee.eu/2012/schema/units/}tTrajectoryPointMini" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOccupantTrajectory", propOrder = {
    "occupantID",
    "spaceRef",
    "occupantTrajectory",
    "a"
})
public class TOccupantTrajectory {

    @XmlElement(required = true)
    protected String occupantID;
    protected String spaceRef;
    protected List<TTrajectoryPoint> occupantTrajectory;
    protected List<TTrajectoryPointMini> a;

    /**
     * Gets the value of the occupantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupantID() {
        return occupantID;
    }

    /**
     * Sets the value of the occupantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupantID(String value) {
        this.occupantID = value;
    }

    /**
     * Gets the value of the spaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpaceRef() {
        return spaceRef;
    }

    /**
     * Sets the value of the spaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpaceRef(String value) {
        this.spaceRef = value;
    }

    /**
     * Gets the value of the occupantTrajectory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the occupantTrajectory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOccupantTrajectory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTrajectoryPoint }
     * 
     * 
     */
    public List<TTrajectoryPoint> getOccupantTrajectory() {
        if (occupantTrajectory == null) {
            occupantTrajectory = new ArrayList<TTrajectoryPoint>();
        }
        return this.occupantTrajectory;
    }

    /**
     * Gets the value of the a property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the a property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTrajectoryPointMini }
     * 
     * 
     */
    public List<TTrajectoryPointMini> getA() {
        if (a == null) {
            a = new ArrayList<TTrajectoryPointMini>();
        }
        return this.a;
    }

}
