//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.event;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tOccupantMovementEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOccupantMovementEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="occupantRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromSpaceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toSpaceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOccupantMovementEvent", propOrder = {
    "time",
    "occupantRef",
    "fromSpaceRef",
    "toSpaceRef"
})
public class TOccupantMovementEvent {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar time;
    @XmlElement(required = true)
    protected String occupantRef;
    protected String fromSpaceRef;
    protected String toSpaceRef;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the occupantRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupantRef() {
        return occupantRef;
    }

    /**
     * Sets the value of the occupantRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupantRef(String value) {
        this.occupantRef = value;
    }

    /**
     * Gets the value of the fromSpaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromSpaceRef() {
        return fromSpaceRef;
    }

    /**
     * Sets the value of the fromSpaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromSpaceRef(String value) {
        this.fromSpaceRef = value;
    }

    /**
     * Gets the value of the toSpaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToSpaceRef() {
        return toSpaceRef;
    }

    /**
     * Sets the value of the toSpaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToSpaceRef(String value) {
        this.toSpaceRef = value;
    }

}
