//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrentUnitEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CurrentUnitEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Ampere"/>
 *     &lt;enumeration value="milliAmpere"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CurrentUnitEnum")
@XmlEnum
public enum CurrentUnitEnum {

    @XmlEnumValue("Ampere")
    AMPERE("Ampere"),
    @XmlEnumValue("milliAmpere")
    MILLI_AMPERE("milliAmpere");
    private final String value;

    CurrentUnitEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CurrentUnitEnum fromValue(String v) {
        for (CurrentUnitEnum c: CurrentUnitEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
