//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lengthUnitEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="lengthUnitEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Kilometers"/>
 *     &lt;enumeration value="Meters"/>
 *     &lt;enumeration value="Centimeters"/>
 *     &lt;enumeration value="Millimeters"/>
 *     &lt;enumeration value="Miles"/>
 *     &lt;enumeration value="Yards"/>
 *     &lt;enumeration value="Feet"/>
 *     &lt;enumeration value="Inches"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "lengthUnitEnum")
@XmlEnum
public enum LengthUnitEnum {

    @XmlEnumValue("Kilometers")
    KILOMETERS("Kilometers"),
    @XmlEnumValue("Meters")
    METERS("Meters"),
    @XmlEnumValue("Centimeters")
    CENTIMETERS("Centimeters"),
    @XmlEnumValue("Millimeters")
    MILLIMETERS("Millimeters"),
    @XmlEnumValue("Miles")
    MILES("Miles"),
    @XmlEnumValue("Yards")
    YARDS("Yards"),
    @XmlEnumValue("Feet")
    FEET("Feet"),
    @XmlEnumValue("Inches")
    INCHES("Inches");
    private final String value;

    LengthUnitEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LengthUnitEnum fromValue(String v) {
        for (LengthUnitEnum c: LengthUnitEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
