//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for processValueRefEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="processValueRefEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="nextActivity"/>
 *     &lt;enumeration value="waitingTime"/>
 *     &lt;enumeration value="executionTime"/>
 *     &lt;enumeration value="transportTime"/>
 *     &lt;enumeration value="timeOfUse"/>
 *     &lt;enumeration value="concurrency"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "processValueRefEnum")
@XmlEnum
public enum ProcessValueRefEnum {


    /**
     * Distribution over an activity's likelihood per nextActivityRef. Requires activityRef attribute.
     * 
     */
    @XmlEnumValue("nextActivity")
    NEXT_ACTIVITY("nextActivity"),

    /**
     * Distribution over an activity's waiting time. Requires activityRef attribute.
     * 
     */
    @XmlEnumValue("waitingTime")
    WAITING_TIME("waitingTime"),

    /**
     * Distribution over an activity's execution time. Requires activityRef attribute.
     * 
     */
    @XmlEnumValue("executionTime")
    EXECUTION_TIME("executionTime"),

    /**
     * Distribution over an activity's transport time. Requires activityRef attribute.
     * 
     */
    @XmlEnumValue("transportTime")
    TRANSPORT_TIME("transportTime"),

    /**
     * Distribution over an activity's used equipment time of use. Requires activityRef and usedEquipmentRef attributes.
     * 
     */
    @XmlEnumValue("timeOfUse")
    TIME_OF_USE("timeOfUse"),

    /**
     * Distribution over an activity's or process time of exclusive usage where in terms of percent 0 percent means non-exclusive-utilization and 100 percent means utilization-dedicated to the given refs.
     * 
     */
    @XmlEnumValue("concurrency")
    CONCURRENCY("concurrency"),

    /**
     * Distribution over a process value. Requires "otherRef" attribute.
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ProcessValueRefEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProcessValueRefEnum fromValue(String v) {
        for (ProcessValueRefEnum c: ProcessValueRefEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
