//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stationIdTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stationIdTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="WMO"/>
 *     &lt;enumeration value="WBAN"/>
 *     &lt;enumeration value="ICAO"/>
 *     &lt;enumeration value="NWSLI"/>
 *     &lt;enumeration value="FAACallSign"/>
 *     &lt;enumeration value="COOP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stationIdTypeEnum")
@XmlEnum
public enum StationIdTypeEnum {


    /**
     * A five-digit station identifier assigned by the World Meteorological Organization (WMO), used for international weather data exchange and station documentation.
     * 
     */
    WMO("WMO"),

    /**
     * Weather-Bureau-Army-Navy station id. A five-digit station identifier used at National Climatic Data Center (NCDC) for digital data storage and general station identification purposes.
     * 
     */
    WBAN("WBAN"),

    /**
     * A 4-letter indicator for geographical locations throughout the world, managed by the International Civil Aviation Organization (ICAO).
     * 
     */
    ICAO("ICAO"),

    /**
     * A 3- to 5-character alpha-numeric identifier assigned by the US National Weather Service (NWS), used for site identification in the NWS communications systems (e.g. AFOS, ROSA, SHEF, etc.).
     * 
     */
    NWSLI("NWSLI"),

    /**
     * An alpha-numeric identifier of up to 4-characters managed by the USDT Federal Aviation Administration (FAA), used for site identification of airports, weather stations and other sites vital to navigation.
     * 
     */
    @XmlEnumValue("FAACallSign")
    FAA_CALL_SIGN("FAACallSign"),

    /**
     * A 6-digit number identifying a station in the NWS Cooperative Network.
     * 
     */
    COOP("COOP");
    private final String value;

    StationIdTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StationIdTypeEnum fromValue(String v) {
        for (StationIdTypeEnum c: StationIdTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
