//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOccupantPositionValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOccupantPositionValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="occupantid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="possition" type="{http://www.adapt4ee.eu/2012/schema/units/}tPossitionValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOccupantPositionValue", propOrder = {
    "occupantid",
    "possition"
})
public class TOccupantPositionValue {

    @XmlElement(required = true)
    protected String occupantid;
    @XmlElement(required = true)
    protected TPossitionValue possition;

    /**
     * Gets the value of the occupantid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupantid() {
        return occupantid;
    }

    /**
     * Sets the value of the occupantid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupantid(String value) {
        this.occupantid = value;
    }

    /**
     * Gets the value of the possition property.
     * 
     * @return
     *     possible object is
     *     {@link TPossitionValue }
     *     
     */
    public TPossitionValue getPossition() {
        return possition;
    }

    /**
     * Sets the value of the possition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPossitionValue }
     *     
     */
    public void setPossition(TPossitionValue value) {
        this.possition = value;
    }

}
