//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPossitionValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPossitionValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="x" type="{http://www.adapt4ee.eu/2012/schema/units/}tLengthValue"/>
 *         &lt;element name="y" type="{http://www.adapt4ee.eu/2012/schema/units/}tLengthValue"/>
 *         &lt;element name="z" type="{http://www.adapt4ee.eu/2012/schema/units/}tLengthValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPossitionValue", propOrder = {
    "x",
    "y",
    "z"
})
public class TPossitionValue {

    @XmlElement(required = true)
    protected TLengthValue x;
    @XmlElement(required = true)
    protected TLengthValue y;
    @XmlElement(required = true)
    protected TLengthValue z;

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link TLengthValue }
     *     
     */
    public TLengthValue getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLengthValue }
     *     
     */
    public void setX(TLengthValue value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link TLengthValue }
     *     
     */
    public TLengthValue getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLengthValue }
     *     
     */
    public void setY(TLengthValue value) {
        this.y = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link TLengthValue }
     *     
     */
    public TLengthValue getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLengthValue }
     *     
     */
    public void setZ(TLengthValue value) {
        this.z = value;
    }

}
