//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.units;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for velocityUnitEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="velocityUnitEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="MetersPerSecond"/>
 *     &lt;enumeration value="MilesPerHour"/>
 *     &lt;enumeration value="Knots"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "velocityUnitEnum")
@XmlEnum
public enum VelocityUnitEnum {

    @XmlEnumValue("MetersPerSecond")
    METERS_PER_SECOND("MetersPerSecond"),
    @XmlEnumValue("MilesPerHour")
    MILES_PER_HOUR("MilesPerHour"),
    @XmlEnumValue("Knots")
    KNOTS("Knots");
    private final String value;

    VelocityUnitEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VelocityUnitEnum fromValue(String v) {
        for (VelocityUnitEnum c: VelocityUnitEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
