//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 08:28:42 AM CET 
//


package eu.adapt4ee._2012.schema.env;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import eu.adapt4ee._2012.schema.units.TLengthValue;
import eu.adapt4ee._2012.schema.units.TStationIdValue;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.adapt4ee._2012.schema.env package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TLocationName_QNAME = new QName("", "Name");
    private final static QName _TLocationDescription_QNAME = new QName("", "Description");
    private final static QName _TLocationElevation_QNAME = new QName("", "Elevation");
    private final static QName _TLocationStationId_QNAME = new QName("", "StationId");
    private final static QName _TLocationLatitude_QNAME = new QName("", "Latitude");
    private final static QName _TLocationLongitude_QNAME = new QName("", "Longitude");
    private final static QName _TLocationZipcodeOrPostalCode_QNAME = new QName("", "ZipcodeOrPostalCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.adapt4ee._2012.schema.env
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TAverageWeather }
     * 
     */
    public TAverageWeather createTAverageWeather() {
        return new TAverageWeather();
    }

    /**
     * Create an instance of {@link TLocation }
     * 
     */
    public TLocation createTLocation() {
        return new TLocation();
    }

    /**
     * Create an instance of {@link TAverageWeather.AverageWeatherForTime }
     * 
     */
    public TAverageWeather.AverageWeatherForTime createTAverageWeatherAverageWeatherForTime() {
        return new TAverageWeather.AverageWeatherForTime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name", scope = TLocation.class)
    public JAXBElement<String> createTLocationName(String value) {
        return new JAXBElement<String>(_TLocationName_QNAME, String.class, TLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description", scope = TLocation.class)
    public JAXBElement<String> createTLocationDescription(String value) {
        return new JAXBElement<String>(_TLocationDescription_QNAME, String.class, TLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLengthValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Elevation", scope = TLocation.class)
    public JAXBElement<TLengthValue> createTLocationElevation(TLengthValue value) {
        return new JAXBElement<TLengthValue>(_TLocationElevation_QNAME, TLengthValue.class, TLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStationIdValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StationId", scope = TLocation.class)
    public JAXBElement<TStationIdValue> createTLocationStationId(TStationIdValue value) {
        return new JAXBElement<TStationIdValue>(_TLocationStationId_QNAME, TStationIdValue.class, TLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Latitude", scope = TLocation.class)
    public JAXBElement<BigDecimal> createTLocationLatitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TLocationLatitude_QNAME, BigDecimal.class, TLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Longitude", scope = TLocation.class)
    public JAXBElement<BigDecimal> createTLocationLongitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TLocationLongitude_QNAME, BigDecimal.class, TLocation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZipcodeOrPostalCode", scope = TLocation.class)
    public JAXBElement<String> createTLocationZipcodeOrPostalCode(String value) {
        return new JAXBElement<String>(_TLocationZipcodeOrPostalCode_QNAME, String.class, TLocation.class, value);
    }

}
