//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.30 at 08:28:42 AM CET 
//


package eu.adapt4ee._2012.schema.env;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import eu.adapt4ee._2012.schema.units.TLengthValue;
import eu.adapt4ee._2012.schema.units.TStationIdValue;


/**
 * <p>Java class for tLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="StationId" type="{http://www.adapt4ee.eu/2012/schema/units/}tStationIdValue" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ZipcodeOrPostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Elevation" type="{http://www.adapt4ee.eu/2012/schema/units/}tLengthValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLocation", propOrder = {
    "stationIdAndNameAndDescription"
})
public class TLocation {

    @XmlElementRefs({
        @XmlElementRef(name = "Elevation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Name", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ZipcodeOrPostalCode", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Description", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Latitude", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Longitude", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StationId", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> stationIdAndNameAndDescription;

    /**
     * Gets the value of the stationIdAndNameAndDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stationIdAndNameAndDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStationIdAndNameAndDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TLengthValue }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link TStationIdValue }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getStationIdAndNameAndDescription() {
        if (stationIdAndNameAndDescription == null) {
            stationIdAndNameAndDescription = new ArrayList<JAXBElement<?>>();
        }
        return this.stationIdAndNameAndDescription;
    }

}
