//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.device;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.adapt4ee._2012.schema.device package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.adapt4ee._2012.schema.device
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSensorMeasurement }
     * 
     */
    public TSensorMeasurement createTSensorMeasurement() {
        return new TSensorMeasurement();
    }

    /**
     * Create an instance of {@link TSensor }
     * 
     */
    public TSensor createTSensor() {
        return new TSensor();
    }

    /**
     * Create an instance of {@link SensorType }
     * 
     */
    public SensorType createSensorType() {
        return new SensorType();
    }

    /**
     * Create an instance of {@link TSensorType }
     * 
     */
    public TSensorType createTSensorType() {
        return new TSensorType();
    }

    /**
     * Create an instance of {@link TSensorMeasurement.RFID }
     * 
     */
    public TSensorMeasurement.RFID createTSensorMeasurementRFID() {
        return new TSensorMeasurement.RFID();
    }

    /**
     * Create an instance of {@link TSensorMeasurement.SmartSensor }
     * 
     */
    public TSensorMeasurement.SmartSensor createTSensorMeasurementSmartSensor() {
        return new TSensorMeasurement.SmartSensor();
    }

}
