//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.kpi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.adapt4ee._2012.schema.kpi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.adapt4ee._2012.schema.kpi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TKeyPerformanceIndicator }
     * 
     */
    public TKeyPerformanceIndicator createTKeyPerformanceIndicator() {
        return new TKeyPerformanceIndicator();
    }

    /**
     * Create an instance of {@link TKeyPerformanceIndicator.BusinessKPI }
     * 
     */
    public TKeyPerformanceIndicator.BusinessKPI createTKeyPerformanceIndicatorBusinessKPI() {
        return new TKeyPerformanceIndicator.BusinessKPI();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics }
     * 
     */
    public TSimulatorStatistics createTSimulatorStatistics() {
        return new TSimulatorStatistics();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.ProcessLogs }
     * 
     */
    public TSimulatorStatistics.ProcessLogs createTSimulatorStatisticsProcessLogs() {
        return new TSimulatorStatistics.ProcessLogs();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.BusinessProcessActivityTimeSeries }
     * 
     */
    public TSimulatorStatistics.BusinessProcessActivityTimeSeries createTSimulatorStatisticsBusinessProcessActivityTimeSeries() {
        return new TSimulatorStatistics.BusinessProcessActivityTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorCO2TimeSeries }
     * 
     */
    public TSimulatorStatistics.IndoorCO2TimeSeries createTSimulatorStatisticsIndoorCO2TimeSeries() {
        return new TSimulatorStatistics.IndoorCO2TimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorIlluminanceTimeSeries }
     * 
     */
    public TSimulatorStatistics.IndoorIlluminanceTimeSeries createTSimulatorStatisticsIndoorIlluminanceTimeSeries() {
        return new TSimulatorStatistics.IndoorIlluminanceTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorAirHumidityTimeSeries }
     * 
     */
    public TSimulatorStatistics.IndoorAirHumidityTimeSeries createTSimulatorStatisticsIndoorAirHumidityTimeSeries() {
        return new TSimulatorStatistics.IndoorAirHumidityTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorAirTemperatureTimeSeries }
     * 
     */
    public TSimulatorStatistics.IndoorAirTemperatureTimeSeries createTSimulatorStatisticsIndoorAirTemperatureTimeSeries() {
        return new TSimulatorStatistics.IndoorAirTemperatureTimeSeries();
    }

    /**
     * Create an instance of {@link TEventTrace }
     * 
     */
    public TEventTrace createTEventTrace() {
        return new TEventTrace();
    }

    /**
     * Create an instance of {@link TAgentBasedSimulationModuleOutput }
     * 
     */
    public TAgentBasedSimulationModuleOutput createTAgentBasedSimulationModuleOutput() {
        return new TAgentBasedSimulationModuleOutput();
    }

    /**
     * Create an instance of {@link TKeyPerformanceIndicator.EnergyKPI }
     * 
     */
    public TKeyPerformanceIndicator.EnergyKPI createTKeyPerformanceIndicatorEnergyKPI() {
        return new TKeyPerformanceIndicator.EnergyKPI();
    }

    /**
     * Create an instance of {@link TKeyPerformanceIndicator.ComfortKPI }
     * 
     */
    public TKeyPerformanceIndicator.ComfortKPI createTKeyPerformanceIndicatorComfortKPI() {
        return new TKeyPerformanceIndicator.ComfortKPI();
    }

    /**
     * Create an instance of {@link TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant }
     * 
     */
    public TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant createTKeyPerformanceIndicatorBusinessKPIAverageWorkEfficiencyPerOccupant() {
        return new TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.EquipmentArtifactUsageTimeSeries }
     * 
     */
    public TSimulatorStatistics.EquipmentArtifactUsageTimeSeries createTSimulatorStatisticsEquipmentArtifactUsageTimeSeries() {
        return new TSimulatorStatistics.EquipmentArtifactUsageTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.HVACUsageTimeSeries }
     * 
     */
    public TSimulatorStatistics.HVACUsageTimeSeries createTSimulatorStatisticsHVACUsageTimeSeries() {
        return new TSimulatorStatistics.HVACUsageTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.PMV }
     * 
     */
    public TSimulatorStatistics.PMV createTSimulatorStatisticsPMV() {
        return new TSimulatorStatistics.PMV();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.LightingUsageTimeSeries }
     * 
     */
    public TSimulatorStatistics.LightingUsageTimeSeries createTSimulatorStatisticsLightingUsageTimeSeries() {
        return new TSimulatorStatistics.LightingUsageTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.OccupantBusinessActivityTimeSeries }
     * 
     */
    public TSimulatorStatistics.OccupantBusinessActivityTimeSeries createTSimulatorStatisticsOccupantBusinessActivityTimeSeries() {
        return new TSimulatorStatistics.OccupantBusinessActivityTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.OccupantBuildingElementOccupationTimeSeries }
     * 
     */
    public TSimulatorStatistics.OccupantBuildingElementOccupationTimeSeries createTSimulatorStatisticsOccupantBuildingElementOccupationTimeSeries() {
        return new TSimulatorStatistics.OccupantBuildingElementOccupationTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.BuildingElementUsageTimeSeries }
     * 
     */
    public TSimulatorStatistics.BuildingElementUsageTimeSeries createTSimulatorStatisticsBuildingElementUsageTimeSeries() {
        return new TSimulatorStatistics.BuildingElementUsageTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.BuildingElementOccupancyTimeSeries }
     * 
     */
    public TSimulatorStatistics.BuildingElementOccupancyTimeSeries createTSimulatorStatisticsBuildingElementOccupancyTimeSeries() {
        return new TSimulatorStatistics.BuildingElementOccupancyTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.OutdoorAirTemperatureTimeSeries }
     * 
     */
    public TSimulatorStatistics.OutdoorAirTemperatureTimeSeries createTSimulatorStatisticsOutdoorAirTemperatureTimeSeries() {
        return new TSimulatorStatistics.OutdoorAirTemperatureTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.OutdoorAirHumidityTimeSeries }
     * 
     */
    public TSimulatorStatistics.OutdoorAirHumidityTimeSeries createTSimulatorStatisticsOutdoorAirHumidityTimeSeries() {
        return new TSimulatorStatistics.OutdoorAirHumidityTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.OutdoorIlluminanceTimeSeries }
     * 
     */
    public TSimulatorStatistics.OutdoorIlluminanceTimeSeries createTSimulatorStatisticsOutdoorIlluminanceTimeSeries() {
        return new TSimulatorStatistics.OutdoorIlluminanceTimeSeries();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.ProcessLogs.ProcessLog }
     * 
     */
    public TSimulatorStatistics.ProcessLogs.ProcessLog createTSimulatorStatisticsProcessLogsProcessLog() {
        return new TSimulatorStatistics.ProcessLogs.ProcessLog();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.BusinessProcessActivityTimeSeries.BusinessProcessActivityTime }
     * 
     */
    public TSimulatorStatistics.BusinessProcessActivityTimeSeries.BusinessProcessActivityTime createTSimulatorStatisticsBusinessProcessActivityTimeSeriesBusinessProcessActivityTime() {
        return new TSimulatorStatistics.BusinessProcessActivityTimeSeries.BusinessProcessActivityTime();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorCO2TimeSeries.InternalCO2Value }
     * 
     */
    public TSimulatorStatistics.IndoorCO2TimeSeries.InternalCO2Value createTSimulatorStatisticsIndoorCO2TimeSeriesInternalCO2Value() {
        return new TSimulatorStatistics.IndoorCO2TimeSeries.InternalCO2Value();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorIlluminanceTimeSeries.InternalIlluminanceValue }
     * 
     */
    public TSimulatorStatistics.IndoorIlluminanceTimeSeries.InternalIlluminanceValue createTSimulatorStatisticsIndoorIlluminanceTimeSeriesInternalIlluminanceValue() {
        return new TSimulatorStatistics.IndoorIlluminanceTimeSeries.InternalIlluminanceValue();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorAirHumidityTimeSeries.InternalHumidityValue }
     * 
     */
    public TSimulatorStatistics.IndoorAirHumidityTimeSeries.InternalHumidityValue createTSimulatorStatisticsIndoorAirHumidityTimeSeriesInternalHumidityValue() {
        return new TSimulatorStatistics.IndoorAirHumidityTimeSeries.InternalHumidityValue();
    }

    /**
     * Create an instance of {@link TSimulatorStatistics.IndoorAirTemperatureTimeSeries.InternalTemperatureValue }
     * 
     */
    public TSimulatorStatistics.IndoorAirTemperatureTimeSeries.InternalTemperatureValue createTSimulatorStatisticsIndoorAirTemperatureTimeSeriesInternalTemperatureValue() {
        return new TSimulatorStatistics.IndoorAirTemperatureTimeSeries.InternalTemperatureValue();
    }

    /**
     * Create an instance of {@link TEventTrace.EventRecord }
     * 
     */
    public TEventTrace.EventRecord createTEventTraceEventRecord() {
        return new TEventTrace.EventRecord();
    }

}
