//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adapt4ee.eu/2012/schema/kpi/")
package eu.adapt4ee._2012.schema.kpi;
