//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.kpi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAgentBasedSimulationModuleOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAgentBasedSimulationModuleOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="simulationID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keyPerformanceIndicator" type="{http://www.adapt4ee.eu/2012/schema/kpi/}tKeyPerformanceIndicator"/>
 *         &lt;element name="simulatorStatistics" type="{http://www.adapt4ee.eu/2012/schema/kpi/}tSimulatorStatistics"/>
 *         &lt;element name="eventTrace" type="{http://www.adapt4ee.eu/2012/schema/kpi/}tEventTrace"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAgentBasedSimulationModuleOutput", propOrder = {
    "simulationID",
    "keyPerformanceIndicator",
    "simulatorStatistics",
    "eventTrace"
})
public class TAgentBasedSimulationModuleOutput {

    @XmlElement(required = true)
    protected String simulationID;
    @XmlElement(required = true)
    protected TKeyPerformanceIndicator keyPerformanceIndicator;
    @XmlElement(required = true)
    protected TSimulatorStatistics simulatorStatistics;
    @XmlElement(required = true)
    protected TEventTrace eventTrace;

    /**
     * Gets the value of the simulationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimulationID() {
        return simulationID;
    }

    /**
     * Sets the value of the simulationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimulationID(String value) {
        this.simulationID = value;
    }

    /**
     * Gets the value of the keyPerformanceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link TKeyPerformanceIndicator }
     *     
     */
    public TKeyPerformanceIndicator getKeyPerformanceIndicator() {
        return keyPerformanceIndicator;
    }

    /**
     * Sets the value of the keyPerformanceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKeyPerformanceIndicator }
     *     
     */
    public void setKeyPerformanceIndicator(TKeyPerformanceIndicator value) {
        this.keyPerformanceIndicator = value;
    }

    /**
     * Gets the value of the simulatorStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link TSimulatorStatistics }
     *     
     */
    public TSimulatorStatistics getSimulatorStatistics() {
        return simulatorStatistics;
    }

    /**
     * Sets the value of the simulatorStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSimulatorStatistics }
     *     
     */
    public void setSimulatorStatistics(TSimulatorStatistics value) {
        this.simulatorStatistics = value;
    }

    /**
     * Gets the value of the eventTrace property.
     * 
     * @return
     *     possible object is
     *     {@link TEventTrace }
     *     
     */
    public TEventTrace getEventTrace() {
        return eventTrace;
    }

    /**
     * Sets the value of the eventTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEventTrace }
     *     
     */
    public void setEventTrace(TEventTrace value) {
        this.eventTrace = value;
    }

}
