//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.kpi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tEventTrace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEventTrace">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventRecord" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="occupantRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="occupantGroupRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="spaceRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="equipmentRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="activityType" type="{http://www.adapt4ee.eu/2012/schema/kpi/}ActivityEnumerator" minOccurs="0"/>
 *                   &lt;element name="processRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="processInstanceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="activityRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEventTrace", propOrder = {
    "eventRecord"
})
public class TEventTrace {

    protected List<TEventTrace.EventRecord> eventRecord;

    /**
     * Gets the value of the eventRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEventTrace.EventRecord }
     * 
     * 
     */
    public List<TEventTrace.EventRecord> getEventRecord() {
        if (eventRecord == null) {
            eventRecord = new ArrayList<TEventTrace.EventRecord>();
        }
        return this.eventRecord;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="occupantRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="occupantGroupRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="spaceRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="equipmentRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="activityType" type="{http://www.adapt4ee.eu/2012/schema/kpi/}ActivityEnumerator" minOccurs="0"/>
     *         &lt;element name="processRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="processInstanceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="activityRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeStamp",
        "occupantRef",
        "occupantGroupRef",
        "spaceRef",
        "equipmentRef",
        "activityType",
        "processRef",
        "processInstanceRef",
        "activityRef"
    })
    public static class EventRecord {

        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeStamp;
        @XmlElement(required = true)
        protected String occupantRef;
        @XmlElement(required = true)
        protected String occupantGroupRef;
        @XmlElement(required = true)
        protected String spaceRef;
        protected String equipmentRef;
        protected ActivityEnumerator activityType;
        protected String processRef;
        protected String processInstanceRef;
        protected String activityRef;

        /**
         * Gets the value of the timeStamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeStamp() {
            return timeStamp;
        }

        /**
         * Sets the value of the timeStamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeStamp(XMLGregorianCalendar value) {
            this.timeStamp = value;
        }

        /**
         * Gets the value of the occupantRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOccupantRef() {
            return occupantRef;
        }

        /**
         * Sets the value of the occupantRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOccupantRef(String value) {
            this.occupantRef = value;
        }

        /**
         * Gets the value of the occupantGroupRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOccupantGroupRef() {
            return occupantGroupRef;
        }

        /**
         * Sets the value of the occupantGroupRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOccupantGroupRef(String value) {
            this.occupantGroupRef = value;
        }

        /**
         * Gets the value of the spaceRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpaceRef() {
            return spaceRef;
        }

        /**
         * Sets the value of the spaceRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpaceRef(String value) {
            this.spaceRef = value;
        }

        /**
         * Gets the value of the equipmentRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEquipmentRef() {
            return equipmentRef;
        }

        /**
         * Sets the value of the equipmentRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEquipmentRef(String value) {
            this.equipmentRef = value;
        }

        /**
         * Gets the value of the activityType property.
         * 
         * @return
         *     possible object is
         *     {@link ActivityEnumerator }
         *     
         */
        public ActivityEnumerator getActivityType() {
            return activityType;
        }

        /**
         * Sets the value of the activityType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActivityEnumerator }
         *     
         */
        public void setActivityType(ActivityEnumerator value) {
            this.activityType = value;
        }

        /**
         * Gets the value of the processRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessRef() {
            return processRef;
        }

        /**
         * Sets the value of the processRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessRef(String value) {
            this.processRef = value;
        }

        /**
         * Gets the value of the processInstanceRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessInstanceRef() {
            return processInstanceRef;
        }

        /**
         * Sets the value of the processInstanceRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessInstanceRef(String value) {
            this.processInstanceRef = value;
        }

        /**
         * Gets the value of the activityRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivityRef() {
            return activityRef;
        }

        /**
         * Sets the value of the activityRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivityRef(String value) {
            this.activityRef = value;
        }

    }

}
