//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.02 at 11:00:40 PM CEST 
//


package eu.adapt4ee._2012.schema.kpi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.adapt4ee._2012.schema.units.TDurationValue;
import eu.adapt4ee._2012.schema.units.TEmissionValue;
import eu.adapt4ee._2012.schema.units.TEnergyPerAreaValue;
import eu.adapt4ee._2012.schema.units.TEnergyValue;
import eu.adapt4ee._2012.schema.units.TOtherValue;
import eu.adapt4ee._2012.schema.units.TUnitlessValue;


/**
 * 
 * 				TODO to the same for Lighting and HVAC emissions
 * 			
 * 
 * <p>Java class for tKeyPerformanceIndicator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tKeyPerformanceIndicator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmissionsFactor" type="{http://www.adapt4ee.eu/2012/schema/units/}tOtherValue" minOccurs="0"/>
 *         &lt;element name="equipmentEmissionsPerTime" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="energyKPI">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TotalEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *                   &lt;element name="TotalEquipmentEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *                   &lt;element name="TotalLightingEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *                   &lt;element name="TotalHVACEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
 *                   &lt;element name="TotalEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                   &lt;element name="TotalEquipmentEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                   &lt;element name="TotalAnnualLightingEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                   &lt;element name="TotalLightingEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                   &lt;element name="TotalAnnualHVACEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                   &lt;element name="BuildingOperationalPerformance" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
 *                   &lt;element name="TotalEnergyConsumptionPerArea" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyPerAreaValue" minOccurs="0"/>
 *                   &lt;element name="TotalAnnualEnergyEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                   &lt;element name="TotalHVACEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="businessKPI">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AverageWorkEfficiency" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
 *                   &lt;element name="AverageBuildingUsage" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
 *                   &lt;element name="AverageEquipmentUsage" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
 *                   &lt;element name="AverageBusinessProcessUtilisation" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="AverageRoleUtilisation" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
 *                   &lt;element name="AverageProcessCycleTime" type="{http://www.adapt4ee.eu/2012/schema/units/}tDurationValue" minOccurs="0"/>
 *                   &lt;element name="AverageWorkEfficiencyPerOccupant" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="workEfficiency" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
 *                             &lt;element name="occupantRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="comfortKPI">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AverageOvercrowdingFactor" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
 *                   &lt;element name="AveragePMV" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
 *                   &lt;element name="AveragePPD" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tKeyPerformanceIndicator", propOrder = {
    "emissionsFactor",
    "equipmentEmissionsPerTime",
    "energyKPI",
    "businessKPI",
    "comfortKPI"
})
public class TKeyPerformanceIndicator {

    @XmlElement(name = "EmissionsFactor")
    protected TOtherValue emissionsFactor;
    protected List<String> equipmentEmissionsPerTime;
    @XmlElement(required = true)
    protected TKeyPerformanceIndicator.EnergyKPI energyKPI;
    @XmlElement(required = true)
    protected TKeyPerformanceIndicator.BusinessKPI businessKPI;
    @XmlElement(required = true)
    protected TKeyPerformanceIndicator.ComfortKPI comfortKPI;

    /**
     * Gets the value of the emissionsFactor property.
     * 
     * @return
     *     possible object is
     *     {@link TOtherValue }
     *     
     */
    public TOtherValue getEmissionsFactor() {
        return emissionsFactor;
    }

    /**
     * Sets the value of the emissionsFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOtherValue }
     *     
     */
    public void setEmissionsFactor(TOtherValue value) {
        this.emissionsFactor = value;
    }

    /**
     * Gets the value of the equipmentEmissionsPerTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentEmissionsPerTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentEmissionsPerTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEquipmentEmissionsPerTime() {
        if (equipmentEmissionsPerTime == null) {
            equipmentEmissionsPerTime = new ArrayList<String>();
        }
        return this.equipmentEmissionsPerTime;
    }

    /**
     * Gets the value of the energyKPI property.
     * 
     * @return
     *     possible object is
     *     {@link TKeyPerformanceIndicator.EnergyKPI }
     *     
     */
    public TKeyPerformanceIndicator.EnergyKPI getEnergyKPI() {
        return energyKPI;
    }

    /**
     * Sets the value of the energyKPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKeyPerformanceIndicator.EnergyKPI }
     *     
     */
    public void setEnergyKPI(TKeyPerformanceIndicator.EnergyKPI value) {
        this.energyKPI = value;
    }

    /**
     * Gets the value of the businessKPI property.
     * 
     * @return
     *     possible object is
     *     {@link TKeyPerformanceIndicator.BusinessKPI }
     *     
     */
    public TKeyPerformanceIndicator.BusinessKPI getBusinessKPI() {
        return businessKPI;
    }

    /**
     * Sets the value of the businessKPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKeyPerformanceIndicator.BusinessKPI }
     *     
     */
    public void setBusinessKPI(TKeyPerformanceIndicator.BusinessKPI value) {
        this.businessKPI = value;
    }

    /**
     * Gets the value of the comfortKPI property.
     * 
     * @return
     *     possible object is
     *     {@link TKeyPerformanceIndicator.ComfortKPI }
     *     
     */
    public TKeyPerformanceIndicator.ComfortKPI getComfortKPI() {
        return comfortKPI;
    }

    /**
     * Sets the value of the comfortKPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKeyPerformanceIndicator.ComfortKPI }
     *     
     */
    public void setComfortKPI(TKeyPerformanceIndicator.ComfortKPI value) {
        this.comfortKPI = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AverageWorkEfficiency" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
     *         &lt;element name="AverageBuildingUsage" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
     *         &lt;element name="AverageEquipmentUsage" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
     *         &lt;element name="AverageBusinessProcessUtilisation" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="AverageRoleUtilisation" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
     *         &lt;element name="AverageProcessCycleTime" type="{http://www.adapt4ee.eu/2012/schema/units/}tDurationValue" minOccurs="0"/>
     *         &lt;element name="AverageWorkEfficiencyPerOccupant" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="workEfficiency" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
     *                   &lt;element name="occupantRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "averageWorkEfficiency",
        "averageBuildingUsage",
        "averageEquipmentUsage",
        "averageBusinessProcessUtilisation",
        "averageRoleUtilisation",
        "averageProcessCycleTime",
        "averageWorkEfficiencyPerOccupant"
    })
    public static class BusinessKPI {

        @XmlElement(name = "AverageWorkEfficiency")
        protected TUnitlessValue averageWorkEfficiency;
        @XmlElement(name = "AverageBuildingUsage", required = true)
        protected TUnitlessValue averageBuildingUsage;
        @XmlElement(name = "AverageEquipmentUsage", required = true)
        protected TUnitlessValue averageEquipmentUsage;
        @XmlElement(name = "AverageBusinessProcessUtilisation")
        protected List<TUnitlessValue> averageBusinessProcessUtilisation;
        @XmlElement(name = "AverageRoleUtilisation")
        protected TUnitlessValue averageRoleUtilisation;
        @XmlElement(name = "AverageProcessCycleTime")
        protected TDurationValue averageProcessCycleTime;
        @XmlElement(name = "AverageWorkEfficiencyPerOccupant")
        protected List<TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant> averageWorkEfficiencyPerOccupant;

        /**
         * Gets the value of the averageWorkEfficiency property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAverageWorkEfficiency() {
            return averageWorkEfficiency;
        }

        /**
         * Sets the value of the averageWorkEfficiency property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAverageWorkEfficiency(TUnitlessValue value) {
            this.averageWorkEfficiency = value;
        }

        /**
         * Gets the value of the averageBuildingUsage property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAverageBuildingUsage() {
            return averageBuildingUsage;
        }

        /**
         * Sets the value of the averageBuildingUsage property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAverageBuildingUsage(TUnitlessValue value) {
            this.averageBuildingUsage = value;
        }

        /**
         * Gets the value of the averageEquipmentUsage property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAverageEquipmentUsage() {
            return averageEquipmentUsage;
        }

        /**
         * Sets the value of the averageEquipmentUsage property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAverageEquipmentUsage(TUnitlessValue value) {
            this.averageEquipmentUsage = value;
        }

        /**
         * Gets the value of the averageBusinessProcessUtilisation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the averageBusinessProcessUtilisation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAverageBusinessProcessUtilisation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TUnitlessValue }
         * 
         * 
         */
        public List<TUnitlessValue> getAverageBusinessProcessUtilisation() {
            if (averageBusinessProcessUtilisation == null) {
                averageBusinessProcessUtilisation = new ArrayList<TUnitlessValue>();
            }
            return this.averageBusinessProcessUtilisation;
        }

        /**
         * Gets the value of the averageRoleUtilisation property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAverageRoleUtilisation() {
            return averageRoleUtilisation;
        }

        /**
         * Sets the value of the averageRoleUtilisation property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAverageRoleUtilisation(TUnitlessValue value) {
            this.averageRoleUtilisation = value;
        }

        /**
         * Gets the value of the averageProcessCycleTime property.
         * 
         * @return
         *     possible object is
         *     {@link TDurationValue }
         *     
         */
        public TDurationValue getAverageProcessCycleTime() {
            return averageProcessCycleTime;
        }

        /**
         * Sets the value of the averageProcessCycleTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDurationValue }
         *     
         */
        public void setAverageProcessCycleTime(TDurationValue value) {
            this.averageProcessCycleTime = value;
        }

        /**
         * Gets the value of the averageWorkEfficiencyPerOccupant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the averageWorkEfficiencyPerOccupant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAverageWorkEfficiencyPerOccupant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant }
         * 
         * 
         */
        public List<TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant> getAverageWorkEfficiencyPerOccupant() {
            if (averageWorkEfficiencyPerOccupant == null) {
                averageWorkEfficiencyPerOccupant = new ArrayList<TKeyPerformanceIndicator.BusinessKPI.AverageWorkEfficiencyPerOccupant>();
            }
            return this.averageWorkEfficiencyPerOccupant;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="workEfficiency" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
         *         &lt;element name="occupantRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "workEfficiency",
            "occupantRef"
        })
        public static class AverageWorkEfficiencyPerOccupant {

            @XmlElement(required = true)
            protected TUnitlessValue workEfficiency;
            @XmlElement(required = true)
            protected String occupantRef;

            /**
             * Gets the value of the workEfficiency property.
             * 
             * @return
             *     possible object is
             *     {@link TUnitlessValue }
             *     
             */
            public TUnitlessValue getWorkEfficiency() {
                return workEfficiency;
            }

            /**
             * Sets the value of the workEfficiency property.
             * 
             * @param value
             *     allowed object is
             *     {@link TUnitlessValue }
             *     
             */
            public void setWorkEfficiency(TUnitlessValue value) {
                this.workEfficiency = value;
            }

            /**
             * Gets the value of the occupantRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOccupantRef() {
                return occupantRef;
            }

            /**
             * Sets the value of the occupantRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOccupantRef(String value) {
                this.occupantRef = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AverageOvercrowdingFactor" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
     *         &lt;element name="AveragePMV" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
     *         &lt;element name="AveragePPD" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "averageOvercrowdingFactor",
        "averagePMV",
        "averagePPD"
    })
    public static class ComfortKPI {

        @XmlElement(name = "AverageOvercrowdingFactor")
        protected TUnitlessValue averageOvercrowdingFactor;
        @XmlElement(name = "AveragePMV")
        protected TUnitlessValue averagePMV;
        @XmlElement(name = "AveragePPD", required = true)
        protected TUnitlessValue averagePPD;

        /**
         * Gets the value of the averageOvercrowdingFactor property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAverageOvercrowdingFactor() {
            return averageOvercrowdingFactor;
        }

        /**
         * Sets the value of the averageOvercrowdingFactor property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAverageOvercrowdingFactor(TUnitlessValue value) {
            this.averageOvercrowdingFactor = value;
        }

        /**
         * Gets the value of the averagePMV property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAveragePMV() {
            return averagePMV;
        }

        /**
         * Sets the value of the averagePMV property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAveragePMV(TUnitlessValue value) {
            this.averagePMV = value;
        }

        /**
         * Gets the value of the averagePPD property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getAveragePPD() {
            return averagePPD;
        }

        /**
         * Sets the value of the averagePPD property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setAveragePPD(TUnitlessValue value) {
            this.averagePPD = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TotalEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
     *         &lt;element name="TotalEquipmentEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
     *         &lt;element name="TotalLightingEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
     *         &lt;element name="TotalHVACEnergyConsumption" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyValue" minOccurs="0"/>
     *         &lt;element name="TotalEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *         &lt;element name="TotalEquipmentEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *         &lt;element name="TotalAnnualLightingEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *         &lt;element name="TotalLightingEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *         &lt;element name="TotalAnnualHVACEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *         &lt;element name="BuildingOperationalPerformance" type="{http://www.adapt4ee.eu/2012/schema/units/}tUnitlessValue" minOccurs="0"/>
     *         &lt;element name="TotalEnergyConsumptionPerArea" type="{http://www.adapt4ee.eu/2012/schema/units/}tEnergyPerAreaValue" minOccurs="0"/>
     *         &lt;element name="TotalAnnualEnergyEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *         &lt;element name="TotalHVACEmissions" type="{http://www.adapt4ee.eu/2012/schema/units/}tEmissionValue" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalEnergyConsumption",
        "totalEquipmentEnergyConsumption",
        "totalLightingEnergyConsumption",
        "totalHVACEnergyConsumption",
        "totalEmissions",
        "totalEquipmentEmissions",
        "totalAnnualLightingEmissions",
        "totalLightingEmissions",
        "totalAnnualHVACEmissions",
        "buildingOperationalPerformance",
        "totalEnergyConsumptionPerArea",
        "totalAnnualEnergyEmissions",
        "totalHVACEmissions"
    })
    public static class EnergyKPI {

        @XmlElement(name = "TotalEnergyConsumption")
        protected TEnergyValue totalEnergyConsumption;
        @XmlElement(name = "TotalEquipmentEnergyConsumption")
        protected TEnergyValue totalEquipmentEnergyConsumption;
        @XmlElement(name = "TotalLightingEnergyConsumption")
        protected TEnergyValue totalLightingEnergyConsumption;
        @XmlElement(name = "TotalHVACEnergyConsumption")
        protected TEnergyValue totalHVACEnergyConsumption;
        @XmlElement(name = "TotalEmissions")
        protected TEmissionValue totalEmissions;
        @XmlElement(name = "TotalEquipmentEmissions")
        protected TEmissionValue totalEquipmentEmissions;
        @XmlElement(name = "TotalAnnualLightingEmissions")
        protected TEmissionValue totalAnnualLightingEmissions;
        @XmlElement(name = "TotalLightingEmissions")
        protected TEmissionValue totalLightingEmissions;
        @XmlElement(name = "TotalAnnualHVACEmissions")
        protected TEmissionValue totalAnnualHVACEmissions;
        @XmlElement(name = "BuildingOperationalPerformance")
        protected TUnitlessValue buildingOperationalPerformance;
        @XmlElement(name = "TotalEnergyConsumptionPerArea")
        protected TEnergyPerAreaValue totalEnergyConsumptionPerArea;
        @XmlElement(name = "TotalAnnualEnergyEmissions")
        protected TEmissionValue totalAnnualEnergyEmissions;
        @XmlElement(name = "TotalHVACEmissions")
        protected TEmissionValue totalHVACEmissions;

        /**
         * Gets the value of the totalEnergyConsumption property.
         * 
         * @return
         *     possible object is
         *     {@link TEnergyValue }
         *     
         */
        public TEnergyValue getTotalEnergyConsumption() {
            return totalEnergyConsumption;
        }

        /**
         * Sets the value of the totalEnergyConsumption property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnergyValue }
         *     
         */
        public void setTotalEnergyConsumption(TEnergyValue value) {
            this.totalEnergyConsumption = value;
        }

        /**
         * Gets the value of the totalEquipmentEnergyConsumption property.
         * 
         * @return
         *     possible object is
         *     {@link TEnergyValue }
         *     
         */
        public TEnergyValue getTotalEquipmentEnergyConsumption() {
            return totalEquipmentEnergyConsumption;
        }

        /**
         * Sets the value of the totalEquipmentEnergyConsumption property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnergyValue }
         *     
         */
        public void setTotalEquipmentEnergyConsumption(TEnergyValue value) {
            this.totalEquipmentEnergyConsumption = value;
        }

        /**
         * Gets the value of the totalLightingEnergyConsumption property.
         * 
         * @return
         *     possible object is
         *     {@link TEnergyValue }
         *     
         */
        public TEnergyValue getTotalLightingEnergyConsumption() {
            return totalLightingEnergyConsumption;
        }

        /**
         * Sets the value of the totalLightingEnergyConsumption property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnergyValue }
         *     
         */
        public void setTotalLightingEnergyConsumption(TEnergyValue value) {
            this.totalLightingEnergyConsumption = value;
        }

        /**
         * Gets the value of the totalHVACEnergyConsumption property.
         * 
         * @return
         *     possible object is
         *     {@link TEnergyValue }
         *     
         */
        public TEnergyValue getTotalHVACEnergyConsumption() {
            return totalHVACEnergyConsumption;
        }

        /**
         * Sets the value of the totalHVACEnergyConsumption property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnergyValue }
         *     
         */
        public void setTotalHVACEnergyConsumption(TEnergyValue value) {
            this.totalHVACEnergyConsumption = value;
        }

        /**
         * Gets the value of the totalEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalEmissions() {
            return totalEmissions;
        }

        /**
         * Sets the value of the totalEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalEmissions(TEmissionValue value) {
            this.totalEmissions = value;
        }

        /**
         * Gets the value of the totalEquipmentEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalEquipmentEmissions() {
            return totalEquipmentEmissions;
        }

        /**
         * Sets the value of the totalEquipmentEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalEquipmentEmissions(TEmissionValue value) {
            this.totalEquipmentEmissions = value;
        }

        /**
         * Gets the value of the totalAnnualLightingEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalAnnualLightingEmissions() {
            return totalAnnualLightingEmissions;
        }

        /**
         * Sets the value of the totalAnnualLightingEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalAnnualLightingEmissions(TEmissionValue value) {
            this.totalAnnualLightingEmissions = value;
        }

        /**
         * Gets the value of the totalLightingEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalLightingEmissions() {
            return totalLightingEmissions;
        }

        /**
         * Sets the value of the totalLightingEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalLightingEmissions(TEmissionValue value) {
            this.totalLightingEmissions = value;
        }

        /**
         * Gets the value of the totalAnnualHVACEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalAnnualHVACEmissions() {
            return totalAnnualHVACEmissions;
        }

        /**
         * Sets the value of the totalAnnualHVACEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalAnnualHVACEmissions(TEmissionValue value) {
            this.totalAnnualHVACEmissions = value;
        }

        /**
         * Gets the value of the buildingOperationalPerformance property.
         * 
         * @return
         *     possible object is
         *     {@link TUnitlessValue }
         *     
         */
        public TUnitlessValue getBuildingOperationalPerformance() {
            return buildingOperationalPerformance;
        }

        /**
         * Sets the value of the buildingOperationalPerformance property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUnitlessValue }
         *     
         */
        public void setBuildingOperationalPerformance(TUnitlessValue value) {
            this.buildingOperationalPerformance = value;
        }

        /**
         * Gets the value of the totalEnergyConsumptionPerArea property.
         * 
         * @return
         *     possible object is
         *     {@link TEnergyPerAreaValue }
         *     
         */
        public TEnergyPerAreaValue getTotalEnergyConsumptionPerArea() {
            return totalEnergyConsumptionPerArea;
        }

        /**
         * Sets the value of the totalEnergyConsumptionPerArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnergyPerAreaValue }
         *     
         */
        public void setTotalEnergyConsumptionPerArea(TEnergyPerAreaValue value) {
            this.totalEnergyConsumptionPerArea = value;
        }

        /**
         * Gets the value of the totalAnnualEnergyEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalAnnualEnergyEmissions() {
            return totalAnnualEnergyEmissions;
        }

        /**
         * Sets the value of the totalAnnualEnergyEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalAnnualEnergyEmissions(TEmissionValue value) {
            this.totalAnnualEnergyEmissions = value;
        }

        /**
         * Gets the value of the totalHVACEmissions property.
         * 
         * @return
         *     possible object is
         *     {@link TEmissionValue }
         *     
         */
        public TEmissionValue getTotalHVACEmissions() {
            return totalHVACEmissions;
        }

        /**
         * Sets the value of the totalHVACEmissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEmissionValue }
         *     
         */
        public void setTotalHVACEmissions(TEmissionValue value) {
            this.totalHVACEmissions = value;
        }

    }

}
